apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-service
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
      nodePort: 30003
    - protocol: TCP
      name: grpc
      port: 7001
      targetPort: 7001
      nodePort: 30004
